# Generated by Django 4.1.7 on 2023-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Марки Машины')),
                ('description', models.TextField(verbose_name='Описание Машины')),
                ('image', models.ImageField(upload_to='')),
                ('car_type', models.CharField(choices=[('Жигули', 'Жигули'), ('Мазда', 'Мазда'), ('Тойота', 'Тойота'), ('Лексус', 'Лексус'), ('Мерседес', 'Мерседес')], max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('video', models.URLField()),
            ],
        ),
    ]
