# Generated by Django 4.1.7 on 2023-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_post_url_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_post',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
