# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_post_url_post_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
