# Generated by Django 4.1.7 on 2023-03-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_post_url_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_post',
        ),
    ]
