# Generated by Django 4.1.7 on 2023-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_post_url_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_post',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
