# Generated by Django 4.1.7 on 2023-03-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_post_url_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
