# Generated by Django 4.1.7 on 2023-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
