# Generated by Django 4.1.7 on 2023-03-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
